name: Awesome Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run awesome-lint
        run: npx awesome-lint
